asdf ::= ( ( ( participant ( '->' | '->>' | '-->' | '-->>' )? )
           | ( 'note' ( 'left of' | 'right of' | "over"  )    ) ) participant ':' message ( add-info )? )+

add-info ::= TAB "~~~" ( "{" name-value ( "," name-value )* "}" )? NL body TAB "~~~"

name-value ::= ('"timestamp"' ":" JSON-string)
             | ('"srcInstanceId"' ":" JSON-string)
             | ('"dstInstanceId"' ":" JSON-string)
             | ('"size"' ":" JSON-integer)
             | ('"isSpecial"' ":" 'true')
             | (JSON-string ":" JSON-value)
